version: '3.8'
services:
   db:
     image: mysql:8.2.0
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: drupal
       MYSQL_DATABASE: drupal
       MYSQL_USER:  drupal
       MYSQL_PASSWORD: drupal
   drupal:
     depends_on:
       - db
     image: drupal:10.2.4
     ports:
       - "8000:80"
     restart: always
     environment:
       DRUPAL_DB_HOST: db:3306
       DRUPAL_DB_USER: drupal
       DRUPAL_DB_PASSWORD: drupal
       DRUPAL_DB_NAME: drupal
volumes:
    db_data: {}